# Generated by Django 3.0.13 on 2021-03-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('method', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_file', models.FileField(max_length=300, upload_to='')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.Period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailInput',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.Period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_file', models.FileField(max_length=300, upload_to='')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.Period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataInput',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.IntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.Period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('value', models.IntegerField()),
                ('file_to_send', models.FileField(max_length=300, upload_to='')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.Period')),
            ],
        ),
        migrations.AddIndex(
            model_name='aggregation',
            index=models.Index(fields=['period', 'name'], name='generic_app_period__d93d4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='aggregation',
            constraint=models.UniqueConstraint(fields=('period', 'name'), name='defining_fields_Aggregation'),
        ),
    ]
