# Generated by Django 3.0.13 on 2021-03-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('method', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleCharacter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
