# Generated by Django 3.0.13 on 2021-03-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecharacter',
            name='text',
            field=models.TextField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
